Fixes #16750 - *_selected methods expect params[:host]
theforeman/foreman_discovery pull request #304
Opened 2016-09-30 09:11 UTC by dLobatog

Due to the strong params changes, the methods we override in routes.rb
(architecture_selected, os_selected, medium_selected) do not longer
work.

The reason is that these *_selected methods expect params[:host] to
exist. Other methods like 'taxonomy_scope' also expect params[:host] to
exist.

However, 'discovered_hosts/edit' sends params[:discovered_host], which
is not understood by the HostController.

The discovery plugin should realize that these params will not be
understood by HostController and change them appropriately.

-----------------------------------

This patch merely checks the URL and if it matches 'discovered_hosts' in
some place, it will also set params[:host].

2016-09-30 09:16 UTC, dLobatog commented
@lzap This is a problem with nightly and Foreman 1.13, I think we might want to make a minor relase after this (and other patch I'm making for displaying the templates).

2016-10-13 14:57 UTC, lzap requested changes
LGTM Thanks, Jenkins does not work currently, but I have a failure locally (I rebased on develop everything):

```
1) Error:
ForemanDiscovery::Concerns::HostsControllerTest::hosts controller requests from discovered_hosts url#test_0001_get "host" params from "discovered_hosts" params:
NoMethodError: undefined method `+' for nil:NilClass
    /home/lzap/work/foreman_discovery/test/functional/foreman_discovery/concerns/hosts_controller_extensions_test.rb:17:in `block (2 levels) in <class:HostsControllerTest>'
```

2016-10-13 14:57 UTC, lzap commented on lib/foreman_discovery/engine.rb
>      config.autoload_paths += Dir["#{config.root}/app/controllers/concerns"]
Why adding another path? We already have that on line 13. But if you prefer this path, just move all the concerns into the new folder.

2016-10-13 14:57 UTC, lzap commented on lib/foreman_discovery/engine.rb
> +        ForemanDiscovery::Concerns::HostsControllerExtensions
I'd prefer this on one line. No biggie.

2016-10-13 14:57 UTC, lzap commented on app/controllers/foreman_discovery/concerns/hosts_controller_extensions.rb
> +        return unless request.url.match(/discovered_hosts/).present?
Can you match only path part of url to prevent false execution. To be honest, I'd prefer full comparison of the path rather than regexp.

2016-11-01 14:57 UTC, lzap commented
Ping, I think this is fairly important one. How do you do? :-)

2016-11-02 08:33 UTC, dLobatog commented on lib/foreman_discovery/engine.rb
>      config.autoload_paths += Dir["#{config.root}/app/controllers/concerns"]
Just because a 'HostsControllerExtensions' without scoping it in ForemanDiscovery seemed too generic and possibly another plugin would use that.

2016-11-02 08:38 UTC, dLobatog commented on app/controllers/foreman_discovery/concerns/hosts_controller_extensions.rb
> +        return unless request.url.match(/discovered_hosts/).present?
I'm not sure what you mean, do you want me to check if 'discovered_hosts' is included in the URL part after request.host (that is, the path) or what exactly..?

2016-11-02 14:17 UTC, lzap commented on app/controllers/foreman_discovery/concerns/hosts_controller_extensions.rb
> +        return unless request.url.match(/discovered_hosts/).present?
So my concern is these is an url like `/some/url?param=discovered_hosts` that could match. AFAIR we don't have this one, but we could we.

My proposal is either match only the `path` element or at least add slash: `/\/discovered_hosts\//`.

2016-11-02 14:18 UTC, lzap commented on lib/foreman_discovery/engine.rb
>      config.autoload_paths += Dir["#{config.root}/app/controllers/concerns"]
Ok that's fine, we should move everything in a separate PR perhaps.

2016-11-18 14:58 UTC, dLobatog commented
Repushed so that it matches on `request.path` rather than `request.url`. Thanks for the review @lzap 😄

2016-11-21 11:41 UTC, dLobatog commented
@lzap looks like integration tests are broken in Discovery?

2016-11-21 11:41 UTC, dLobatog commented
@lzap looks like integration tests are broken in Discovery?

2016-11-21 11:41 UTC, dLobatog commented
@lzap looks like integration tests are broken in Discovery?

2016-11-21 11:41 UTC, dLobatog commented
@lzap looks like integration tests are broken in Discovery?

2016-11-21 11:41 UTC, dLobatog commented
@lzap looks like integration tests are broken in Discovery?

2016-11-21 16:46 UTC, dLobatog commented
[test]

2016-12-09 14:04 UTC, merged

2016-12-09 14:05 UTC, lzap commented
I was just about to start digging to find out why this happens downstream. Apologize for the late reply. Thanks!