Fixes #16890 - prevent discovery of managed hosts
theforeman/foreman_discovery pull request #324
Opened 2017-01-10 13:23 UTC by lzap

Users were reporting inconsistent records, I implemented dirty workaround the other day:

https://github.com/theforeman/foreman_discovery/pull/311

Now I found the root cause finally, when existing (managed) host was there,
discovery process treated it as discovered host and made some changes
incorrecty. This patch prevents that, adds a test and removes the dirty
workaround.

2017-01-16 16:25 UTC, timogoebel requested changes

2017-01-16 16:25 UTC, timogoebel commented on app/models/host/discovered.rb
> +    raise ::Foreman::Exception.new(N_("Host already exists as managed: #{host.name}/#{bootif_mac}")) if host.type != "Host::Discovered"
.new("Host already exists as managed: %s", "#{host.name}/#{bootif_mac}")

to generate the ERF code correctly?

2017-01-20 12:25 UTC, dLobatog commented on app/models/host/discovered.rb
> +    raise ::Foreman::Exception.new(N_("Host already exists as managed: #{host.name}/#{bootif_mac}")) if host.type != "Host::Discovered"
I'll do this on merge

2017-01-20 12:28 UTC, dLobatog commented
Merged as 210f143bc85c58caeb67e8bf9a5cc2edbe764683 thanks @lzap & @timogoebel

2017-01-20 12:28 UTC, closed without merging