fixes #18677 - adds notification events on host discovery
theforeman/foreman_discovery pull request #328
Opened 2017-02-26 15:30 UTC by ohadlevy

2017-02-26 15:32 UTC, ohadlevy commented
requires https://github.com/theforeman/foreman/pull/4337

2017-02-26 15:34 UTC, ohadlevy commented
![image](https://cloud.githubusercontent.com/assets/20167/23341059/c275abd4-fc49-11e6-9caa-22d8d34a7c8f.png)
![image](https://cloud.githubusercontent.com/assets/20167/23341063/cda4f6c2-fc49-11e6-884c-6f878be02795.png)

2017-02-26 15:35 UTC, ohadlevy commented
/cc @dLobatog

2017-02-26 19:57 UTC, ohadlevy commented
@rohoover anything we can improve to make this notification a bit more interesting? (icons etc?)

2017-02-27 11:23 UTC, ohadlevy commented
@rohoover another question - this implementation allows notification to "expire" once the notification condition is no longer set, for example, once we have an unused discovered hosts the notification remains, but once it is consumed, the notification is removed. I didn't want to provide a link to an invalid action (e.g. go do something with the host and then realize there are none).

2017-02-27 14:43 UTC, Rohoover commented
@ohadlevy 

I would try using an alternate icon in lieu of the "i". One thought to consider, why do you want this particular type of notification to stand out more than any other. I'm not against the idea, I would just want to have clear reasoning why this type is ranked more important than another. 

What is your second question?

2017-02-27 14:48 UTC, ohadlevy commented
@Rohoover 

> I would try using an alternate icon in lieu of the "i". One thought to consider, why do you want this particular type of notification to stand out more than any other. I'm not against the idea, I would just want to have clear reasoning why this type is ranked more important than another.

Discovery, is a means in which unknown /  unconfigured hosts turn on (imagine a company buys 100 new bare metal servers) they auto register to foreman.
The user normally has no way to know discovered hosts are available unless visiting the discovered hosts page.

the idea here is simply to allow users to know they have unused resources that can be "claimed" and start the provisioning/configuration process. 
> 
> What is your second question?

based on our notification implementation, multiple users might receive the notification, however, in the event that one use claimed the resources, we currently remove the notification from all users.

this avoids a user thinking he has a resource he can consume clicking on the link realizing the list of currently avail discovered hosts is empty.

2017-02-27 17:44 UTC, Rohoover commented
@ohadlevy 

I imagined that there would be some notifications that would be persistent and others that would not be removed unless read. So in this example, the text would no longer be bold if read, but remain unless the global situation amongst all users is resolved.

2017-03-07 13:52 UTC, ohadlevy commented
please do not merge, this will be re-written based on the outcome of https://github.com/theforeman/foreman/pull/4339

2017-03-08 14:32 UTC, ohadlevy commented
@dLobatog updated this pr based on the changes in https://github.com/theforeman/foreman/pull/4339

2017-03-08 14:34 UTC, lzap commented
I will leave this one on @dLobatog then :-)

2017-03-09 13:43 UTC, ohadlevy commented
test

2017-03-09 13:43 UTC, ohadlevy commented
foreman pr has been merged.

2017-03-09 15:31 UTC, timogoebel requested changes
... just one thing I noticed during the demo. Not a full review.

2017-03-09 15:31 UTC, timogoebel commented on db/seeds.d/80_discovery_ui_notification.rb
> +    message: _('One or more Hosts has been discovered'),
One ore more hosts _have_ been discovered?

2017-03-09 15:34 UTC, ohadlevy commented
@timogoebel updated.

2017-03-09 15:55 UTC, ohadlevy commented on app/services/foreman_discovery/ui_notifications/new_host.rb
> +        blueprint.notifications.mass_update_expiry
typo: should be blueprint.mass_update_expiry

2017-03-09 16:00 UTC, timogoebel approved these changes

2017-03-09 21:05 UTC, ohadlevy commented on app/models/host/managed_extensions.rb
> +    ForemanDiscovery::UINotifications::DestroyHost.deliver!(self)
this in theory will break running all core tests with foreman's as this extends Host::Managed yet the seeding happens only in discovery, I'm uncertain if this is an issue or not, but if it is we might need to change the way blueprint seeds is loaded in core. (TBH I don't think it should block this pr).

2017-03-09 21:06 UTC, ohadlevy commented on app/models/host/managed_extensions.rb
> +    ForemanDiscovery::UINotifications::DestroyHost.deliver!(self)
Actually, scratch that, I did create a exception handling in core, so this will only warn vs raise.

2017-03-10 09:05 UTC, lzap commented
I have one request, the most important notification imho for discovery would be when host was autoprovisioned using a rule. Currently we add a host comment "Autoprovisioned via rule named 'webserver'" (see `perform_autoprovisioning` method).

Could you also add this kind of notifications: "One or more hosts were autoprovisioned via rule 'webserver'"? Because these events trigger either completely on background (auto mode) or if you mass auto provision more than one and we only report "Autoprovisioning was successful" via bubble. Getting this kind of notification where you can check which host were provisioned using what rules would be very helpful.

If you prefer you can only have one kind of notification with summary list of rules and hosts provisioned, that'd work too I think.

2017-03-10 09:42 UTC, ohadlevy commented
@lzap :+1.  But maybe in another PR?

2017-03-10 17:25 UTC, lzap commented
Oh ok, I mind the PR name. But you could rename, I can still hear your voice "it's super easy to send notification" ;-)

2017-03-10 17:26 UTC, lzap commented
So is this ready to have a full review and test now? I see the core PR was merged, any obstacles?

2017-03-10 18:38 UTC, ohadlevy commented
@lzap from my side its ready

2017-03-13 09:49 UTC, dLobatog commented
Works pretty well - thanks @ohadlevy @lzap @Rohoover

2017-03-13 09:49 UTC, merged

2017-03-13 09:50 UTC, lzap commented
Thanks I was planning to do it today but great! :-)