Fixes #19313 - autoprovisioning NIC association fixed
theforeman/foreman_discovery pull request #346
Opened 2017-05-15 13:28 UTC by lzap

After discovered host is converted to Managed, associated NICs still have their associations set to the original record from the database (`Host::Discovered`), which led the `host.managed?` statement fail in `tftp_ready?` method in TFTP orchestration. This led to TFTP orchestration to be skipped completely, so I added a statement to set the appropriate assotiation explicitly during auto provisioning.

This is a regression and I cannot find the root cause of this, it worked previously. We have reports that both 1.14 and 1.15 are broken.

2017-05-15 19:49 UTC, timogoebel commented
This is a nasty one. Reminds me a lot of e9c626c7258ce405dbe3d95051a5692ac1d87763. Have you tried if a similar approach helps here?

2017-05-16 07:54 UTC, lzap commented on test/test_helper_discovery.rb
> +require "#{root}/factories/discovery_host_related"
This adds possibility to run individual tests:

    be rake test:discovery TEST=/home/lzap/work/foreman_discovery/test/unit/discovered_extensions_test.rb

2017-05-16 07:55 UTC, lzap commented on app/controllers/concerns/foreman/controller/discovered_extensions.rb
> +      Rails.logger.error "Auto provisioning failed: #{host.errors.full_messages.to_sentence}"
This also closes http://projects.theforeman.org/issues/19405

2017-05-16 07:57 UTC, lzap commented
Strange error on Jenkins:

`
NoMethodError: undefined method `split' for nil:NilClass
     (NoMethodError)
/var/lib/workspace/workspace/test_plugin_matrix/database/postgresql/ruby/2.0.0/slave/fast/plugin/test/unit/discovered_extensions_test.rb:176
`

2017-05-16 07:58 UTC, timogoebel commented
> Strange error on Jenkins:

I believe, this can be fixed by replacing `assert_equal nil, blubb` with `assert_ni blubb`.

2017-05-16 08:18 UTC, lzap commented
Adding `refute_nil` there.

2017-05-16 08:19 UTC, lzap commented
Indeed this looks like that was the root cause, I did not notice it. Thank to our weak tests we did not catch it at all. I added tests for autoprovisioning which will verify TFTP and DHCP orchestration.

2017-05-16 09:08 UTC, lzap commented
Hmmm re-testing this today, it does not seem to fix the issue. If I comment out the `#host.clear_association_cache` then it works. Any idea how to approach this?

2017-05-16 12:12 UTC, timogoebel commented
> Any idea how to approach this?

Not at all. I just remember going nuts to come up with this patch.
Maybe we should post to theforeman-dev and ask for help there. Someone might have an idea.

2017-05-17 07:12 UTC, timogoebel commented on test/test_helper_discovery.rb
> +require "#{root}/factories/discovery_host_related"
Would `require_relative` be an alternative to this?

2017-05-17 08:28 UTC, lzap commented on test/test_helper_discovery.rb
> +require "#{root}/factories/discovery_host_related"
I learned something, thanks. It works yeah.

2017-05-17 08:56 UTC, lzap commented
@timogoebel since the regression is fatal and folks cant provision via auto or even API, we might want to remove the line you added for now and try to find better solution later?

To be honest, I don't know why you clear all associations when becomes is overloaded in Host::Base and does exactly that for you:

```ruby
    def becomes(*args)
      became = super
      became.drop_primary_interface_cache
      became.drop_provision_interface_cache
      became.interfaces = self.interfaces
      became
    end
```

2017-05-17 09:44 UTC, timogoebel commented
@lzap : I'd be ok with dropping the line. The overloaded becomes method does not help, might even make things worse.

The issue is iirc, that `host != host.primary_interface.host`. Clearing host's cache doesn't help.

2017-05-17 11:31 UTC, lzap commented
Ok added more tests including check for subnet.tftp in auto provisioning and fixed factories so they now work with or without `TEST=` option in rake. I cannot reproduce the case you were adding the line for, so I am removing it.

2017-05-17 14:45 UTC, lzap commented
I don't understand these, I have `refute_nil` there:

```
NoMethodError: undefined method `split' for nil:NilClass
     (NoMethodError)
/var/lib/workspace/workspace/test_plugin_matrix/database/postgresql/ruby/2.4/slave/fast/plugin/test/unit/discovered_extensions_test.rb:176  
```

2017-05-19 08:33 UTC, lzap commented
Any ETA @timogoebel or @tbrisker this is a nasty regression in both 1.14 and 1.15. Thanks!

2017-05-19 08:34 UTC, lzap commented
Oh wait tests are still red.

2017-05-19 08:38 UTC, timogoebel commented
@lzap : I want to check this out before lunch, hang on...

2017-05-19 08:41 UTC, timogoebel commented on test/factories/discovery_host_related.rb
> +unless FactoryGirl.factories.registered?(:discovered_host)
What is this good for?

2017-05-19 09:16 UTC, lzap commented on test/factories/discovery_host_related.rb
> +unless FactoryGirl.factories.registered?(:discovered_host)
So when you run tests via `TEST=xyz` it loads files in a different way and factory_girl was giving an error - Factory already registered. I could not find any other way than doing this, I want to be able to run all tests and a particular test.

2017-05-19 09:16 UTC, lzap commented
Thanks, do you also see a failure like Jenkins?

2017-05-19 09:42 UTC, timogoebel requested changes

2017-05-19 09:42 UTC, timogoebel commented on test/unit/discovery_attribute_set_test.rb
> -require 'test_helper'
If we do this, we can remove the file `test/test_helper.rb`. It isn't any good.

2017-05-19 09:43 UTC, lzap commented on test/unit/discovery_attribute_set_test.rb
> -require 'test_helper'
I actually can't that does not work, this requires `test_helper` from Foreman and not discovery. It's a mess.

2017-05-19 09:44 UTC, lzap commented on test/unit/discovery_attribute_set_test.rb
> -require 'test_helper'
And core `test_helper` required plugins `test_helper`. You need to be this explicit.

2017-05-19 09:46 UTC, timogoebel commented on test/unit/discovery_attribute_set_test.rb
> -require 'test_helper'
Actually, https://github.com/theforeman/foreman_plugin_template doesn't have a `test/test_helper.rb`at all. So this should be possible.

How about doing this in a separate PR to get the actual fix in fast?

2017-05-19 10:29 UTC, lzap commented
Incorporated your patch and added refute_nils everywhere.

2017-05-19 10:30 UTC, lzap commented
I think I can remove `test_helper.rb` now, let's see what Jenkins does with this version.

2017-05-19 10:31 UTC, lzap commented
Might want to split this into two PRs, one is the line change and the other is test improvement.

2017-05-19 10:31 UTC, lzap commented
Or just two commits.

2017-05-19 10:55 UTC, timogoebel commented
> Or just two commits.

Yep. Makes backporting easier.

What's still missing is the removal of `test/test_helper.rb`

2017-05-19 11:29 UTC, lzap commented
Split into two commits, removed the `test_helper.rb` leftover. If it passes locally for you (green for me) let's merge it and if develop is still broken I will create another PR to fix just jenkins tests.

2017-05-19 11:51 UTC, timogoebel approved these changes

2017-05-19 11:51 UTC, merged

2017-05-19 11:52 UTC, timogoebel commented
Merged, thanks @lzap.