[WIP] Fixes #19440 - Integration test provisioning discovered hosts
theforeman/foreman_discovery pull request #354
Opened 2017-06-14 07:28 UTC by bastilian

This is a start to add integration tests and to have a base for scenarios of bugs.
The first tests cover the provisioning modal and ensure it passes on the parameters, including the hostgroup_id, as a prerequisite for setting inherited values like the domain[1]

The test data still needs to be rewritten to use the factories for hostgroup, location and organization.

I would like to add a few more tests for the overview page, before it is done.
Are there any other tests that might be good to have right away?

[1] http://projects.theforeman.org/issues/19445

2017-06-15 07:59 UTC, lzap reviewed
Good start, but you seem to check parameters only, what usually breaks is that the form won't accept the entry and errors out via either Rails errors or hard 500 error.

Would it be possible to simply submit the form and then check we landed on Host Detail page somehow?

2017-06-15 07:59 UTC, lzap commented on test/integration/discovered_hosts_test.rb
> +    discovered_host.save
I'd perhaps do `save!` so we are sure there is at least one host, I mean if this breaks, all the mass-action tests like reboot might just pass silently.

2017-06-15 07:59 UTC, lzap commented on test/integration/discovered_hosts_test.rb
> +      page.find_link('Provision').click
So this click on random Provision link or the first one? Wondering if there are multiple records what happens.

2017-06-15 07:59 UTC, lzap commented on test/integration/discovered_hosts_test.rb
> +        select_from('host_hostgroup_id', discovery_hostgroup.name)
Name vs id is intentional?

2017-06-15 07:59 UTC, lzap commented on test/integration/discovered_hosts_test.rb
> +  describe 'can provision discovered_host' do
I'd add "using Create host link".

2017-06-16 10:00 UTC, bastilian commented
@lzap I've addressed the comments you had.

I will add more tests to touch the parts that prepare the host form and test as you suggested that the host form is rendered.

2017-06-19 11:48 UTC, lzap commented
LGTM

2017-06-22 06:20 UTC, bastilian commented
@lzap I've added a test for the form itself and to verify the attributes are set from the hostgroup.

For some reason now the issue with the domain (and other attributes) not being set correctly in the Integration test, however when performing the same manually in the UI, the attributes **are** correctly set.

I've added a fix[1] for it, but i hope to find out why it is happening in the tests now and have a better one soon.

2017-07-17 06:33 UTC, ares commented
It seems tests are broken - `NoMethodError: undefined method `notifications' for nil:NilClass...`, not sure if this is caused by the PR though

2017-07-17 08:21 UTC, lzap commented
I think I found the issue - if you look into `domain` factory it always sets organization and location explicitly (Organization 1/Location 1) but you discover the host without any taxonomy. Depending of the context of the app, Domain will not likely present the value so you can't really choose it.

When you test this in UI hosts are always assigned an organization (there is a fallback mechanism - taxonomy of detected subnet is used, if not found then initial taxonomy is assigned). So you can't really ever discover a host without taxonomy.

Can you try again with setting taxonomy explicitly? Then remove the domain workaround you implemented. Maybe we should add a DiscoveredHost validator that makes sure taxonomy is always set, this can break some old tests we have tho.

2017-08-08 12:41 UTC, lzap commented
Rebased and trying it locally but getting this:

    Can't find entry point 'vendor' in webpack manifest

Any clue?

2017-08-09 06:27 UTC, bastilian commented
@lzap I encounter(ed) the same issue. The issue in my case was caused by webpack, that returened "Invalid Host header" for assets. If that is in your case too, a remedy is to disable the host check in webpack with adding `disableHostCheck: false` to [webpack.config.js](https://github.com/theforeman/foreman/blob/develop/config/webpack.config.js#L150)

2017-09-08 13:38 UTC, bastilian commented
@lzap The integration tests now have Location and Organization set and the domain check passes now without my attempted fix.

2017-09-27 07:32 UTC, lzap commented on db/migrate/20150714144500_review_discovery_permissions.rb
> +      end
Please rebase and this can go I believe.

2017-09-27 07:50 UTC, lzap commented on test/integration/discovered_hosts_test.rb
> +    @discovered_host = FactoryGirl.create(:discovered_host, :with_facts)
Our API explicitly creates taxonomy for discovered hosts, I was wondering if you could move the taxonomy let blocks here and set it explicitly here as well.

2017-09-27 07:50 UTC, lzap commented
Allright core fixed let's re [test]

2017-10-17 11:28 UTC, lzap commented
Mind rebase? :-)

2017-10-26 07:43 UTC, lzap commented
I rebased ontop of develop which is finally green (again yeah!) but still getting these JS errors.

2017-10-31 14:01 UTC, bastilian commented
@lzap The JS errors are gone. There are (now) still tests failing:

```
  1) Error:
DiscoveredHostsTest::edit form#test_0001_it is a host form:
Capybara::Poltergeist::StatusFailError: Request to 'http://127.0.0.1:33743/discovered_hosts' failed to reach server, check DNS and/or server status - Timed out with no open resource requests
    test/test_helper.rb:35:in `before_setup'

  2) Error:
DiscoveredHostsControllerTest#test_edit_form_quick_submit:
ActiveRecord::RecordNotFound: Couldn't find Host::Managed with 'id'=33 [WHERE "hosts"."type" IN ('Host::Managed')]
    app/models/host.rb:15:in `method_missing'
    test/active_support_test_case_helper.rb:113:in `disable_taxonomies'

  3) Error:
NewHostNotificationTest#test_0002_multiple discovered hosts should generate only one notification:
NoMethodError: undefined method `notifications' for nil:NilClass
    

  4) Failure:
NewHostNotificationTest#test_0001_new discovered host should generate a notification [/var/lib/workspace/workspace/test_plugin_pull_request/database/postgresql/label/fast/ruby/2.2/plugin/test/unit/ui_notifications/new_host_test.rb:5]:
Expected nil to be truthy.
```

1. is an issue which happens in core tests as well without a fix for it yet. The other test seem to fail, as they miss seed data. 

These failing tests should probably be fixed in another PR, or?

2017-11-01 10:47 UTC, tbrisker requested changes

2017-11-01 10:47 UTC, tbrisker commented on test/integration/discovered_hosts_test.rb
> +  let(:discovered_host) { FactoryGirl.create(:discovered_host, :with_facts) }
This needs to be changed to FactoryBot

2017-11-01 10:47 UTC, tbrisker commented on test/integration/discovered_hosts_test.rb
> +        FactoryGirl.create(:hostgroup, :with_os,
these too

2017-11-02 09:15 UTC, lzap commented
Yeah thanks, finally getting there! :)

2017-11-02 11:06 UTC, bastilian commented
@tbrisker Change to FactoryBot is done.

2017-11-02 12:08 UTC, lzap commented
Aaaand core is broken again :-)

2017-11-02 12:15 UTC, lzap commented
Ok it's our test what is failing, why blueprint is now `nil` ?

NoMethodError: undefined method `notifications' for nil:NilClass
     (NoMethodError)
/var/lib/workspace/workspace/test_plugin_pull_request@2/database/mysql/label/fast/ruby/2.2/plugin/test/unit/ui_notifications/destroy_host_test.rb:6

2017-11-03 10:23 UTC, lzap commented
Ok tests are failing locally for the same reason, please take a look.

2017-11-17 15:36 UTC, ares commented
It seems there are still some tests failing :-(

2017-11-29 14:43 UTC, lzap commented
I am getting these locally:

```
Rails logs for test_0001_it passes it on FAILURE:
E

Error:
DiscoveredHostsTest::using Create Host link::with a Location selected#test_0001_it passes it on:
Capybara::Poltergeist::JavascriptError: One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

TypeError: undefined is not an object (evaluating 'tfm.nav.init')
TypeError: undefined is not an object (evaluating 'tfm.nav.init')
    at http://127.0.0.1:39927/assets/application-daecd4ed7147767e48554589a4bced4d637accc3beef1df5d169160640c1d097.js:21648
    at http://127.0.0.1:39927/assets/application-daecd4ed7147767e48554589a4bced4d637accc3beef1df5d169160640c1d097.js:30
    at http://127.0.0.1:39927/webpack/bundle-cf97ad12463c31ce45f1.js:29 in dispatch
    at http://127.0.0.1:39927/webpack/bundle-cf97ad12463c31ce45f1.js:29 in handle
    at http://127.0.0.1:39927/webpack/bundle-cf97ad12463c31ce45f1.js:29 in trigger
    at http://127.0.0.1:39927/webpack/bundle-cf97ad12463c31ce45f1.js:29
    at http://127.0.0.1:39927/webpack/bundle-cf97ad12463c31ce45f1.js:19 in each
    at http://127.0.0.1:39927/webpack/bundle-cf97ad12463c31ce45f1.js:19 in each
    at http://127.0.0.1:39927/webpack/bundle-cf97ad12463c31ce45f1.js:29 in trigger
    at http://127.0.0.1:39927/assets/application-daecd4ed7147767e48554589a4bced4d637accc3beef1df5d169160640c1d097.js:35 in onLoad
    at http://127.0.0.1:39927/webpack/bundle-cf97ad12463c31ce45f1.js:29 in l
    at http://127.0.0.1:39927/webpack/bundle-cf97ad12463c31ce45f1.js:29 in fireWith
    at http://127.0.0.1:39927/webpack/bundle-cf97ad12463c31ce45f1.js:29 in ready
    at http://127.0.0.1:39927/webpack/bundle-cf97ad12463c31ce45f1.js:19 in u
    /home/lzap/work/foreman_discovery/test/integration/discovered_hosts_test.rb:11:in `block in <class:DiscoveredHostsTest>'
    test/test_helper.rb:35:in `before_setup'
```

2017-11-29 14:49 UTC, tbrisker commented
@lzap - that looks like you need to update your foreman and recompile webpack (`rake webpac:compile`)

2017-12-05 11:14 UTC, bastilian commented
There was one test still failing on CI, which failed locally as well.
It seemed to have been test failing by chance when taxonomies are disabled and the discovered host is in a hostgroup with a subnet not that invalidated the IP provided in the facts for importing. 

All other test passed locally and should now on CI pass as well.

2017-12-07 11:56 UTC, ares commented
[test] to resurrect from dns issues

2017-12-08 09:01 UTC, bastilian commented
@ares :green_heart: once again! \o/

2017-12-08 09:49 UTC, ares commented
Awesome, @lzap can we merge while it's green? :-)

2017-12-11 07:36 UTC, ares commented
@tbrisker could you please update your review? :-)

2017-12-11 08:00 UTC, tbrisker approved these changes

2017-12-11 08:01 UTC, tbrisker commented
@ares If any of my reviews is out of date and already addressed feel free to dismiss it :)

2017-12-11 08:33 UTC, ares commented
yeah, I don't have permissions to do it here :-)

2017-12-11 09:02 UTC, merged

2017-12-11 09:02 UTC, lzap commented
Ok looks good to me, thanks @bastilian for such an effort.