Fixes #20162 - Fix the modal
theforeman/foreman_discovery pull request #357
Opened 2017-06-29 11:28 UTC by rahulbajaj0509

2017-06-30 07:06 UTC, dLobatog commented
[test]

2017-06-30 07:30 UTC, rahulbajaj0509 commented
Before:
![modal](https://user-images.githubusercontent.com/10976840/27725264-08ad6e44-5d65-11e7-965d-9a6b79f8d6be.png)

After:
![modalfixed](https://user-images.githubusercontent.com/10976840/27725459-fba7d166-5d65-11e7-8479-13b4ea8c1ef3.png)

2017-06-30 16:55 UTC, dLobatog requested changes
Thanks @rahulbajaj0509 

I'm not sure where the `well` is coming, but it makes a difference on the UI. Can you remove that css class so that it looks like the Patternfly implementation?

http://imgur.com/a/nNJmV

2017-06-30 16:55 UTC, dLobatog commented on app/views/discovered_hosts/_discovered_host_modal.html.erb
> +        <input type="submit" class="btn btn-primary" value="<%= _('Customize') %>" />
I don't really agree with that comment - https://groups.google.com/forum/?fromgroups#!topic/foreman-dev/q_6bxIsEKiU - `Create Host` is more accurate and expected IMO.

2017-06-30 16:55 UTC, dLobatog commented on app/views/discovered_hosts/_discovered_host_modal.html.erb
> +        <input type="submit" class="btn btn-primary" value="<%= _('Customize') %>" />
cc @lzap @rohoover

2017-06-30 18:43 UTC, rahulbajaj0509 commented
Thanks for the review @dLobatog, about the requested changes : 
1) 'well' comes from the 'foreman/foreman' project, if we change it there, then a lot of things will get changed. ( refer - https://github.com/theforeman/foreman/pull/4634 ) 
Therfore, my suggestion would be to keep this model as is.
2) I feel 'Create Host' would be appropriate 👍 , would still wait for lzap and Rohoover for thier input on this :) ( i made changes on the basis of evaluation by Roxanne 😛  )

2017-07-05 13:40 UTC, dLobatog commented
@rohoover Can you take a look at the wording for "Create host"?

2017-07-07 14:02 UTC, Rohoover commented
@dLobatog 

I think when we were doing the review it was brought up that the action wasn't creating a host but customizing because the following steps ask you to actually submit. I was trying to find the recording to verify but haven't located it yet.

2017-07-07 15:49 UTC, rahulbajaj0509 commented
@Rohoover i apologize, i had made these changes before going through the recording, i saw the recording and i was pretty sure that 'customize' is appropriate :) 

you can see the recording at : https://bluejeans.com/s/N0wwf

2017-07-10 08:45 UTC, lzap commented
Sorry for the late reply - I vote for this wording (braces means blue color):

    Cancel - Customize host - [Create host]

Where Customize host is "Provision" and Create host is "Quick Create" in our old terms. I believe the quick path is more common.

2017-07-10 08:48 UTC, rahulbajaj0509 commented
@lzap i think that would be perfect :) Shall make the changes right away!

2017-07-10 15:19 UTC, dLobatog approved these changes

2017-07-10 16:39 UTC, dLobatog commented
[test] - I think we have to rethink how permissions are added to locked roles in this plugin http://ci.theforeman.org/job/test_plugin_pull_request/3874/database=postgresql,label=fast,ruby=2.2/testReport/junit/(root)/CacheManagerTest/test_0001_new_filter_cache_can_be_created_regardless_of_locked_roles/

2017-07-10 18:26 UTC, dLobatog commented
[test] - I think we have to rethink how permissions are added to locked roles in this plugin http://ci.theforeman.org/job/test_plugin_pull_request/3874/database=postgresql,label=fast,ruby=2.2/testReport/junit/(root)/CacheManagerTest/test_0001_new_filter_cache_can_be_created_regardless_of_locked_roles/

2017-07-11 13:50 UTC, dLobatog commented
https://github.com/theforeman/foreman/pull/4657/files should unblock this PR

2017-07-11 20:00 UTC, rahulbajaj0509 commented
@dLobatog , thanks a lot. Executed the tests, all green 👍

2017-07-12 07:03 UTC, lzap commented
[test]

2017-07-13 09:22 UTC, lzap requested changes
Buttons do not work for me, I click on them and nothing happens, except Cancel - that one do cancel tho.

2017-08-08 12:26 UTC, lzap commented
Tests finally fixed [test]. Will re-test shortly.

2017-08-19 11:52 UTC, rahulbajaj0509 commented
Irrelevant tests are failing here, any idea why these tests are failing ?

2017-08-24 08:03 UTC, lzap commented
Please rebase and push again, these were issues in core.

2017-08-24 08:49 UTC, rahulbajaj0509 commented
closing and re-opening for CI trigger.

2017-08-24 08:51 UTC, rahulbajaj0509 commented
[test]

2017-08-30 10:31 UTC, merged

2017-08-30 10:31 UTC, lzap commented
Thanks.