Fixes #20247 - Add welcome page to foreman discovery
theforeman/foreman_discovery pull request #360
Opened 2017-07-10 07:41 UTC by rahulbajaj0509

2017-07-11 07:24 UTC, lzap requested changes
Good, few things.

2017-07-11 07:24 UTC, lzap commented on app/controllers/discovered_hosts_controller.rb
> +
Can you try to override `model_of_controller` instead? Will it work?

2017-07-11 07:24 UTC, lzap commented on app/views/discovered_hosts/welcome.html.erb
> +<% content_for(:title, _("DiscoveredHosts")) %>
Why not `_("Discovered Hosts")` it's a visible title, isn't it?

2017-07-11 07:24 UTC, lzap commented on app/views/discovered_hosts/welcome.html.erb
> +  <p><%= _("You don't have any visible discovered hosts. This plugin enables Foreman to do automatic bare-metal discovery of unknown nodes on the provisioning network.") %></p>
Can you reword and split it to i18n keys:

    <p><%= _("No discovered hosts found in this context.") %>
    <%= _("This page shows discovered bare-metal or virtual nodes waiting to be provisioned.") %></p>

2017-07-11 07:24 UTC, lzap commented on app/views/discovered_hosts/welcome.html.erb
> +  <p><%= link_to _('Learn more about this in the documentation.'), documentation_url("8.0/index.html", {:root_url => 'https://theforeman.org/plugins/foreman_discovery/'})%></p>
Use something like:

    ForemanDiscovery::VERSION.scan(/\d+\.\d+/).first

to get the current stable version number for the URL. Docs are just about to appear there this week.

2017-07-12 07:03 UTC, lzap commented
[test]

2017-07-13 09:17 UTC, lzap commented
Particular reason why you haven't reworded the text? I *think* this would be a good fit:

```
<p><%= _("No discovered hosts found in this context.") %>
<%= _("This page shows discovered bare-metal or virtual nodes waiting to be provisioned.") %></p>
```

2017-07-13 09:24 UTC, rahulbajaj0509 commented
@lzap , (sorry), done :)

2017-07-14 10:36 UTC, lzap commented
[test]

2017-07-14 12:08 UTC, merged

2017-07-14 12:09 UTC, lzap commented
Thanks a lot.