Fixes #20259 - deleted unused scripts, discovery script
theforeman/foreman_discovery pull request #361
Opened 2017-07-10 12:22 UTC by lzap

I have an improved script to do ad-hoc fake hosts discovery. It will become part of the main git repository.

Old scripts can be removed, they are not used anymore (this was from first generation discovery).

2017-07-10 12:23 UTC, lzap commented
You will find this useful @rahulbajaj0509 :-) Please review.

2017-07-13 07:37 UTC, rahulbajaj0509 commented
@lzap , the script was indeed informative :)

Concerned with one thing here:
The fake discovered host is created in the organization that is alphabetically first among all the organizations created and does not get created in the organization i want, is this the correct functionality ?

2017-07-13 08:34 UTC, lzap commented
Yeah, I can perhaps add custom org/loc option, lemme do that. Unfortunately the way it works is super-clunky, read this: https://theforeman.org/plugins/foreman_discovery/9.1/index.html#3.1.3OrganizationsandLocations

2017-07-13 08:51 UTC, lzap commented
Try now! New options org/loc are present. Oh when I was testing this it was not working, reported a bug and fixed it here:

http://projects.theforeman.org/issues/20294

2017-07-13 09:12 UTC, rahulbajaj0509 commented
@lzap Thanks 👍  looks good to me !

2017-07-13 09:12 UTC, lzap commented
Adding a test, @dLobatog this would be also in 9.1.2 if possible.

2017-07-13 16:52 UTC, dLobatog requested changes

2017-07-13 16:52 UTC, dLobatog commented on test/unit/host_discovered_test.rb
> +  test "should setup subnet with org and loc set via settings" do
Please rename this one, two tests have the same name so only one runs I think

2017-07-14 11:35 UTC, lzap commented on test/unit/host_discovered_test.rb
> +  test "should setup subnet with org and loc set via settings" do
Done

2017-07-17 13:38 UTC, dLobatog approved these changes

2017-07-17 13:38 UTC, merged

2017-07-17 13:39 UTC, dLobatog commented
Thanks @lzap !