Fixes #20126 - Enable selective reboot and autoprovision
theforeman/foreman_discovery pull request #364
Opened 2017-07-17 09:44 UTC by rahulbajaj0509

2017-07-17 11:29 UTC, lzap requested changes
Some small nitpick and one comment about the API.

2017-07-17 11:29 UTC, lzap commented on app/helpers/discovered_hosts_helper.rb
> +    actions = [[_('Delete Hosts'), multiple_destroy_discovered_hosts_path, hash_for_multiple_destroy_discovered_hosts_path]]
Please remove "hosts/Hosts" completely.

2017-07-17 11:29 UTC, lzap commented on app/helpers/discovered_hosts_helper.rb
> +    actions <<  [_('Auto Provision Hosts'), multiple_auto_provision_discovered_hosts_path, hash_for_multiple_auto_provision_discovered_hosts_path]
Remove "Hosts" from both actions, let's just keep verb everywhere.

Also re-order the menu in this order please:

* Auto Provision
* Reboot
* Assign Org
* Assign Loc
* Delete

2017-07-17 11:29 UTC, lzap commented on lib/foreman_discovery/engine.rb
> +            :"api/v2/discovered_hosts" => [:refresh_facts, :reboot, :multiple_reboot]
In API context there is no multiple support, our API can only reboot once host and reboot all. Please keep V2 API unchanged in this regard.

We are actually missing reboot_all CLI command from our CLI, so only API for reboot_all and auto_prov_all can be used, not CLI. If you want go ahead and create these options (`--all`) in https://github.com/theforeman/hammer-cli-foreman-discovery

2017-08-04 09:17 UTC, sean797 commented
[test]

2017-08-08 12:24 UTC, lzap commented
Tests finally fixed [test].

Are we missing tests here?

2017-08-09 11:23 UTC, lzap commented
Tests are failing because there are not tests fixed and added here. Code looks good, go ahead.

2017-08-24 08:01 UTC, lzap commented
There are failures which seems related, do you see them locally?

2017-08-24 08:28 UTC, rahulbajaj0509 commented
@lzap yeah, i can see the relevant tests failing, will fix them :)

2017-09-27 07:28 UTC, lzap commented
Let's re [test]

2017-09-27 08:49 UTC, rahulbajaj0509 commented
@lzap the tests for this pr will only pass after the legacy api is cleaned from discovery : https://github.com/theforeman/foreman_discovery/pull/374

2017-10-03 09:47 UTC, lzap commented
We can hopefully [test] now.

2017-10-26 07:51 UTC, lzap commented
Please rebase, getting errors:

```
 1) Error:
Api::V2::DiscoveredHostsControllerTest#test_auto_provision_all_success:
ActionController::UrlGenerationError: No route matches {:action=>"auto_provision_all", :controller=>"api/v2/discovered_hosts"}
    /home/lzap/work/foreman_discovery/test/functional/api/v2/discovered_hosts_controller_test.rb:185:in `test_auto_provision_all_success'

  2) Error:
Api::V2::DiscoveredHostsControllerTest#test_auto_provision_all_no_rule_success:
ActionController::UrlGenerationError: No route matches {:action=>"auto_provision_all", :controller=>"api/v2/discovered_hosts"}
    /home/lzap/work/foreman_discovery/test/functional/api/v2/discovered_hosts_controller_test.rb:196:in `test_auto_provision_all_no_rule_success'

  3) Failure:
DiscoveredHostsControllerTest#test_multiple_auto_provision_no_rule_success [/home/lzap/work/foreman_discovery/test/functional/discovered_hosts_controller_test.rb:251]:
Expected "No hosts selected" to be nil.

  4) Failure:
DiscoveredHostsControllerTest#test_multiple_reboot_failure [/home/lzap/work/foreman_discovery/test/functional/discovered_hosts_controller_test.rb:269]:
not all expectations were satisfied
unsatisfied expectations:
- expected exactly once, not yet invoked: #<AnyInstance:ForemanDiscovery::NodeAPI::PowerService>.reboot(any_parameters)
satisfied expectations:
- allowed any number of times, not yet invoked: Webpack::Rails::Manifest.asset_paths(any_parameters)
- allowed any number of times, not yet invoked: #<AnyInstance:ForemanDiscovery::NodeAPI::PowerService>.reboot(any_parameters)


  5) Failure:
DiscoveredHostsControllerTest#test_multiple_reboot_error [/home/lzap/work/foreman_discovery/test/functional/discovered_hosts_controller_test.rb:279]:
not all expectations were satisfied
unsatisfied expectations:
- expected exactly once, not yet invoked: #<AnyInstance:ForemanDiscovery::NodeAPI::PowerService>.reboot(any_parameters)
satisfied expectations:
- allowed any number of times, not yet invoked: Webpack::Rails::Manifest.asset_paths(any_parameters)
- allowed any number of times, not yet invoked: #<AnyInstance:ForemanDiscovery::NodeAPI::PowerService>.reboot(any_parameters)


  6) Failure:
DiscoveredHostsControllerTest#test_multiple_auto_provision_success [/home/lzap/work/foreman_discovery/test/functional/discovered_hosts_controller_test.rb:233]:
Expected "No hosts selected" to be nil.
```

The PR you refer to was merged, we can go ahead and finish this, thanks a lot!

2018-04-02 07:02 UTC, rahulbajaj0509 commented
Facing this issue, not able to get over this: 

```
bin/rails test _discovery/test/functional/discovered_hosts_controller_test.rb:226

.F

Failure:
DiscoveredHostsControllerTest#test_multiple_reboot_failure [/home/vagrant/foreman_discovery/test/functional/discovered_hosts_controller_test.rb:277]:
Expected response to be a <3XX: redirect>, but was a <403: Forbidden>
```

2018-04-02 10:44 UTC, ik5 commented
@rahulbajaj0509 , I'ved changed `session: set_session_user_default_manager` to `session: set_session_user(User.current)` and it works.

Apparently `set_session_user_default_manager` does not set it as a manager.

2018-04-02 10:54 UTC, rahulbajaj0509 commented
@ik5  thanks a lot! I was stuck with this for a while and your comment was very helpful :)
@lzap we should merge this before we go forward for merging https://github.com/theforeman/foreman_discovery/pull/380, so that we can make appropriate changes there.

2018-04-03 08:22 UTC, lzap approved these changes
Nice, code looks good.

2018-04-03 08:25 UTC, lzap commented
Tests are failing, you removed "Reboot All" button but it's being tested in integration tests.

2018-04-04 10:29 UTC, rahulbajaj0509 commented
@lzap  looks good now?

2018-04-04 14:20 UTC, lzap approved these changes
Thanks green locally.

2018-04-04 14:20 UTC, merged

2018-04-12 08:06 UTC, lzap commented on lib/foreman_discovery/engine.rb
>            }, :resource_type => 'Host'
This is missing some actions, I don't understand why I dont see failures locally but on jenkins:

AccessPermissionsTest.test_0739_route discovered_hosts/submit_multiple_reboot should have a permission that grants access
AccessPermissionsTest.test_0740_route discovered_hosts/submit_multiple_auto_provision should have a permission that grants access

http://ci.theforeman.org/job/test_plugin_matrix/5117/database=postgresql,ruby=2.4,slave=fast/

2018-04-12 08:11 UTC, lzap commented on lib/foreman_discovery/engine.rb
>            }, :resource_type => 'Host'
Oh it does fail locally, cool. Let me fix this.

2018-04-12 08:38 UTC, lzap commented on lib/foreman_discovery/engine.rb
>            }, :resource_type => 'Host'
Merged as 84d8e45