fixes #20450 - change pagination to patternfly style
theforeman/foreman_discovery pull request #367
Opened 2017-07-31 11:49 UTC by ohadlevy

2017-08-01 06:17 UTC, rahulbajaj0509 commented
LGTM 👍

2017-08-01 06:27 UTC, ohadlevy commented
@lzap any idea whats wrong with the tests?

2017-08-02 11:53 UTC, lzap commented
Will take a look shortly.

2017-08-08 12:22 UTC, lzap commented
Tests finally fixed [test].

2017-08-10 10:10 UTC, lzap commented
Please rebase on develop first.

2017-08-10 10:41 UTC, ohadlevy commented
@lzap rebased.

2017-08-17 10:17 UTC, lzap commented on app/controllers/discovered_hosts_controller.rb
> +  end
This should be out of `private` section.

2017-08-17 10:17 UTC, lzap commented
Then rebase please and tests should be green. Well, they randomly fail in core currently.

2017-08-24 07:59 UTC, lzap commented
Ping, what's above please, low effort.

2017-08-24 08:03 UTC, ohadlevy commented
@lzap rebased.

2017-09-17 09:55 UTC, ohadlevy commented
bump?

2017-09-27 07:26 UTC, lzap requested changes
Tests are failing because of encapsulation there.

2017-09-27 07:26 UTC, lzap commented on app/controllers/discovered_hosts_controller.rb
> +  end
@ohadlevy you still have this in `private` section, I believe this causes all tests to fail.

2017-11-20 09:04 UTC, ohadlevy commented
@lzap I've rebased and updated based on your comments, but it seems that the test failures indicate at existing failure in discovery (or its fixtures)? can you please take it over from here?

2017-11-29 15:27 UTC, lzap commented
The resource_class breaks all the tests, the controller is a hack around Edit Form and that's the reason - did not dig into details. I don't have time to take over, feel free to pick up this one.

2017-12-17 17:51 UTC, ohadlevy commented
@rahulbajaj0509 do you feel like picking this one up? I don't have time to work on this atm.

2017-12-17 17:51 UTC, closed without merging