fixes #20497 - host provisioning build mode enabled
theforeman/foreman_discovery pull request #368
Opened 2017-08-03 12:54 UTC by timogoebel

2017-08-08 12:21 UTC, lzap commented
Tests finally fixed [test].

2017-08-10 06:51 UTC, lzap requested changes
One test nitpick, thanks.

2017-08-10 06:51 UTC, lzap commented on test/functional/discovered_hosts_controller_test.rb
> +    host = Host::Discovered.import_host(@facts)
Oh one more thing, can you use this helper instead now:

    host = discover_host_from_facts(@facts)

2017-08-10 07:30 UTC, timogoebel commented
@lzap : Rebased and changed test to use the new helper.

2017-08-10 10:20 UTC, lzap commented
Failures are weird, running locally.

2017-08-10 13:28 UTC, lzap commented
I don't see these errors locally. Fantastic.

2017-08-11 08:25 UTC, lzap commented
I really don't know why core tests fail randomly. @ares could this be related to the new permission validator?

I created a core patch to show Rails logs, maybe we will see something interesting there:

https://github.com/theforeman/foreman/pull/4739

2017-08-11 14:18 UTC, ares commented
sorry, from expected false to be truthy I can't really tell... the permissions changes cause deterministic issues though

2017-08-17 10:09 UTC, lzap commented
Random failures trying again with newer foreman develop [test]

2017-08-17 13:08 UTC, timogoebel commented
once again - [test]

2017-08-24 07:58 UTC, lzap commented
Can you please rebase once again or re-trigger? Develop now seems more stable, still random JS failures but not 600 failures....

2017-08-24 08:50 UTC, timogoebel commented
[test]

2017-08-30 07:46 UTC, timogoebel commented
@lzap: Is this ready to go? Tests are green.

2017-08-30 08:30 UTC, merged

2017-08-30 08:30 UTC, lzap commented
Sure, works great thanks.