Fixes 20450 - Update pagination to patternfly style
theforeman/foreman_discovery pull request #406
Opened 2018-01-17 11:50 UTC by rahulbajaj0509

2018-01-17 13:29 UTC, lzap commented
Nice can you update also discovery rules? That's all we have, works just fine.

2018-01-31 09:49 UTC, lzap commented
[test]

2018-01-31 09:52 UTC, tbrisker requested changes

2018-01-31 09:52 UTC, tbrisker commented on app/controllers/discovered_hosts_controller.rb
> +    ], {:interfaces => :subnet}).paginate(:page => params[:page], :per_page => params[:per_page])
please use `@hosts = resource_base_search_and_page.includes(....` so if something changes in core we won't have to update this as well.

2018-01-31 11:36 UTC, rahulbajaj0509 commented
@tbrisker, works perfectly now.

Looks like:
![screenshot from 2018-01-31 17-02-45](https://user-images.githubusercontent.com/10976840/35621027-e2fc8616-067a-11e8-916f-d2b4c1ee6547.png)

2018-01-31 12:51 UTC, tbrisker approved these changes
LGTM, Thanks @rahulbajaj0509 !

2018-01-31 12:52 UTC, merged