Fixes #16330 - random and MAC name generators
theforeman/foreman_discovery pull request #437
Opened 2018-06-01 13:35 UTC by lzap

With deacon gem as foreman core dependency, it is possible to implement naming discovered hosts via deacon's MAC address generator.

https://github.com/lzap/deacon

This makes a lot of sense because the name stays with server until decommission. It's a feature of deacon gem - same MAC maps to same name. See the README.

2018-06-01 13:36 UTC, lzap commented
This is fun! It needs a small core PR: https://github.com/theforeman/foreman/pull/5637

2018-06-14 07:51 UTC, ik5 requested changes
the tests breaks on me, the reason is that the `ensure` part is not part of a `begin` and not part of a method, but rather inside a block call.

It should be something like that:
```
...
  begin
   ...
  ensure
     Setting[:discovery_naming] = "Fact"
  end
end
```

2018-06-15 07:21 UTC, lzap commented
Yeah, weird it looks like newer version of Ruby supports it, good catch Jenkins! Rebasing, I actually removed those, it's not necessary since Settings are fixture records. They are reset on every test.

2018-06-20 08:14 UTC, dLobatog approved these changes
Thanks, works pretty well @lzap . Can we get the discovery docs updated to include this?

2018-06-20 08:15 UTC, merged