[WIP] Fixes #20549 - Use Multiexception for reboot all method
theforeman/foreman_discovery pull request #457
Opened 2018-09-10 09:54 UTC by rahulbajaj0509

This pr uses https://github.com/theforeman/foreman/pull/5785 for multi-exception. While the pr is still in the [WIP] mode, you can test it by having the  original code in the [hammer](https://github.com/theforeman/hammer-cli-foreman-discovery/pull/38/files#diff-5e45be4d27eedc48fe561b6cf4775195L147)

2018-09-10 09:55 UTC, rahulbajaj0509 commented on app/controllers/discovered_hosts_controller.rb
> +      process_error :error_msg => error_message.first.message, :redirect => :back
this was just for the testing purpose, will remove it.

2018-09-10 10:00 UTC, rahulbajaj0509 commented
Current output looks like: 

![screenshot from 2018-09-10 15-29-53](https://user-images.githubusercontent.com/10976840/45290926-61378c00-b50e-11e8-88a6-1c6655bb3ee7.png)

@lzap one thing i was unable to understand here is that, as shown in the picture above, in the array the error is getting printed twice, not sure how.

2018-09-10 13:06 UTC, lzap commented
If you add `[skip ci]` to the second line of the commit message, it won't do CI. However, it's red because of Rails 5.2 migration.

2018-09-11 07:35 UTC, timogoebel commented on app/controllers/concerns/foreman/controller/discovered_extensions.rb
> +            e = Excpetion.New()
typo here? I guess this should be `StandardError.new`.

2018-09-11 07:53 UTC, lzap requested changes
Overall looks great, this can leave WIP mode now. Couple of things here and there around i18n but good work!

2018-09-11 07:53 UTC, lzap commented on app/controllers/api/v2/discovered_hosts_controller.rb
> +        render :json => ::Foreman::MultiException.new(exceptions,"Errors During Rebooting").json_form
Missing space, also i18n: `::Foreman::MultiException.new(exceptions, N_("Errors during rebooting"))`

2018-09-11 07:53 UTC, lzap commented on app/controllers/concerns/foreman/controller/discovered_extensions.rb
> +            overall_errors << WrappedException.new(e, msg)
Do not use WrappedException if you don't have any exception to wrap. Just use Foreman::Exception and give it some text, then you won't see this twice as well.

2018-09-11 07:53 UTC, lzap commented on app/controllers/concerns/foreman/controller/discovered_extensions.rb
> +      overall_errors << WrappedException.new(Exception.new(), msg)
Ditto, simply use Foreman::Exception and that's it.

2018-09-11 07:53 UTC, lzap commented on app/controllers/concerns/foreman/controller/discovered_extensions.rb
> +      msg = _("No discovered hosts to reboot")
It is important to send messages *untranslated* into Foreman::Exception, see https://projects.theforeman.org/projects/foreman/wiki/Translating. Hint: `_()` vs `N_()`.

2018-10-05 15:58 UTC, rahulbajaj0509 commented
@lzap your suggestion about not wrapping an exception if there is no need to made life so much easy, thanks!

 So i figured out that wrapping the exception [here](https://github.com/theforeman/foreman_discovery/blob/develop/app/models/host/discovered.rb#L163) causes  the exception to be printed twice. 

The `perform_reboot_all` method sends an exception to the `reboot` method mentioned in the above link,
we tend to Wrap that exception again, that is the reason that can see the error printed twice.

For better exception handling i would suggest we  use 
```
diff --git a/app/models/host/discovered.rb b/app/models/host/discovered.rb
index a3fd59f..73a1ca9 100644
--- a/app/models/host/discovered.rb
+++ b/app/models/host/discovered.rb
@@ -224,7 +224,7 @@ class Host::Discovered < ::Host::Base
     resource.reboot
   rescue => e
     ::Foreman::Logging.exception("Unable to reboot #{name}", e)
-    raise ::Foreman::WrappedException.new(e, N_("Unable to reboot %{name} via %{url}: %{msg}"), :name => name, :url => proxy_url, :msg => e.to_s)
+    raise ::Foreman::Exception.new(N_("Unable to reboot %{name} via %{url}: %{msg}"), :name => name, :url => proxy_url, :msg => e.to_s)
   end
```

Also, the output with the above suggestion looks like:
![screenshot from 2018-10-05 21-22-51](https://user-images.githubusercontent.com/10976840/46545749-d6676880-c8e4-11e8-9095-f80aeb08181a.png)

What are your thoughts on this? do you think we should go ahead with the above mentioned changes?

2018-10-08 11:43 UTC, lzap commented
The result image looks great, exactly how I like it, it's simple approach to the problem.

Now, I'd rather keep using wrapped exception in that reboot method, it's good use of this class actually. We send a copy of the message in the wrapped message for one purpose - it's way too long to render WrappedException and we render only the message in the UI because space is limited there (toast error). Just keep it, it won't hurt.

If you want to remove be sure to catch the exception and render it in a better way for example using some hover or expansion button. But I'd just ignore it for now, no biggie.

2018-10-08 11:45 UTC, rahulbajaj0509 commented
Thanks for the go ahead @lzap, will push the changes :)

2019-01-24 07:57 UTC, lzap commented
Pls rebase tests are green now.

2019-01-29 07:20 UTC, lzap commented
Red because of a typo: uninitialized constant Foreman::Controller::DiscoveredExtensions::Excpetion.

2021-02-19 11:19 UTC, rabajaj0509 commented
Let's start re-work on this. It is a really good to have PR. Thank you for your patience with this one.

2021-06-17 06:41 UTC, rabajaj0509 commented
@lzap can you please assign this PR to someone else?

2021-06-17 06:41 UTC, closed without merging

2021-06-18 12:25 UTC, lzap commented
We will pick it from here, thank you!