Fixes #27935 - allow deletion of existing hosts during discovery
theforeman/foreman_discovery pull request #490
Opened 2019-09-25 07:07 UTC by lzap

When there is an existing managed host, discovery process either fail or pass depending on if the existing host has the same MAC provisioning address or just hostname. Hostnames must be unique (due to DNS) however MAC addresses do not. There was a setting to change the behavior to error out explicitly or just ignore and allow discovery of hosts with different hostname but conflicting MAC address.

There is a third solution and that is often asked "delete existing managed host when it exists". This is dangerous because it allows to delete hosts via discovery API, so this feature comes only with explicit setting. Documentation will be updated to reflect this new (dangerous) setting.

2019-09-25 07:08 UTC, lzap commented
@lero in my hotfix I had a typo this is a working version. Tell me if it works for you.

2019-09-25 08:53 UTC, lero commented
Cool. I'll test this one. About the company reference, I'll talk internally about it and let you know. Thank you!

2019-10-01 07:46 UTC, timogoebel approved these changes
Code looks good to me, though I haven't tested it.

2019-10-03 13:51 UTC, lzap commented
@lero does it work? Can we merge?

2019-10-03 13:54 UTC, lero commented
It does. But remember that the settings option didn't show up here and I just removed all the ifs from host/discovered.rb to force the deletion? So I'm not sure if the full patch works :)

2019-10-03 14:07 UTC, lzap commented
@timogoebel I am pretty confident about the deletion/error code, however not so sure about the setting and migration. Could you just migrate and boot up if you see the setting correctly? The migration there is to delete the old setting and to copy original value to the new one.

2019-10-04 09:05 UTC, timogoebel commented
> Could you just migrate and boot up if you see the setting correctly?

I don't see it.

```
irb(main):001:0> Setting.find_by_name('discovery_action_on_existing')
=> nil
```

2019-10-04 09:06 UTC, timogoebel requested changes
We need to investigate why the new setting is not being created.

2019-11-29 16:01 UTC, lzap commented
My dev database is screwed up it seems, I need to get back to this after I start over.

2022-07-14 07:28 UTC, stejskalleos commented
I'm closing the PR since the last update was on Nov 29, 2019

2022-07-14 07:28 UTC, closed without merging