Fixes #30577 - use host importer
theforeman/foreman_discovery pull request #504
Opened 2020-08-05 16:18 UTC by lzap

Fixing tests after https://github.com/theforeman/foreman/pull/7749

2020-08-05 16:27 UTC, ezr-ondrej approved these changes
Just nitpicks, general :+1:

2020-08-05 16:27 UTC, ezr-ondrej commented on app/services/foreman_discovery/host_fact_importer.rb
> +end
missing an trailing line
```suggestion
end

```

2020-08-05 16:27 UTC, ezr-ondrej commented on app/models/host/discovered.rb
> +    importer = ForemanDiscovery::HostFactImporter.new(host)
```suggestion
    importer = ::ForemanDiscovery::HostFactImporter.new(host)
```

2020-08-05 16:27 UTC, ezr-ondrej commented on app/models/host/discovered.rb
> +    ForemanDiscovery::HostFactImporter.new(self).import_facts facts
```suggestion
    ::ForemanDiscovery::HostFactImporter.new(self).import_facts facts
```

2020-08-05 17:31 UTC, ezr-ondrej requested changes
Oh, this one I've missed.

2020-08-05 17:31 UTC, ezr-ondrej commented on app/services/foreman_discovery/host_fact_importer.rb
> +        self.last_report = Time.now
```suggestion
        host.last_report = Time.now
```

2020-08-10 07:32 UTC, lzap commented
Commited them all, I could not get my tests running locally yet so this was/is a blind try :-)

2020-08-10 09:09 UTC, ezr-ondrej approved these changes
Great :+1: WFM

2020-08-10 12:49 UTC, merged