Fixes #31975 - remove uniqueness validation from discovery rules
theforeman/foreman_discovery pull request #532
Opened 2021-02-26 10:31 UTC by rabajaj0509

The PR is a part of fixing the _**priority**_ in Discovery Rules as discussed in https://github.com/theforeman/foreman_discovery/pull/450:
* [ ] Drop priority uniqueness test : 
* [ ] Fix taxonomy scope for discovery rule find process
* [ ] Fix the order of discovery rule processing (and on index page as well): priority first, name second
* [ ] Add organizations/locations to the index page: https://github.com/theforeman/foreman_discovery/pull/531
* [ ] Priority suggestion must be suggested from current organization
<hr />

This PR should only be merged after the taxonomy scope is defined for the rules.

2021-03-04 12:49 UTC, rabajaj0509 commented
I think we can fix the order of discovery rule processing (and on index page as well: priority first, name second) in this PR itself.

2021-04-13 13:53 UTC, lzap requested changes
Sorry for the delay, this is correct.

However we still need to have an index on priority column, we do use it in the `find_discovery_rule` method and it can be useful for the UI index page query. SQL server will take advantage of such index when searching with WHERE conditions on priority and name (as long as priority is first).

There is no need to create composed index for priority + name as there will not be many records with the same priority. Probably just few, up to dozens, that's not very useful index.

2021-04-13 13:53 UTC, lzap commented on db/migrate/20210226102122_remove_priority_score_index_from_discovery_rules.rb
> +end
Let's just keep the index on priority column and not introduce a new one, just drop this migration from the patch completely.

2021-04-14 11:39 UTC, lzap approved these changes
Thank you.

2021-04-14 11:39 UTC, merged