Translation improvements
theforeman/foreman_discovery pull request #599
Opened 2023-05-15 13:27 UTC by stejskalleos

* Extract missing strings for the translations
* Fix interpolations in strings
* Update config for the transifex-cli
* Update *.po files

2023-05-17 10:42 UTC, stejskalleos commented
`foreman_discovery` is broken, it's not failing due to my changes

2023-05-17 11:03 UTC, ekohl approved these changes
Thanks!

2023-05-17 11:04 UTC, ekohl requested changes, later dismissed
On second thought, looks like this doesn't update the `.mo` files which are included in the repo.

2023-05-17 11:05 UTC, ekohl commented on foreman_discovery.gemspec
> +  warn "WARNING: File #{mo} outdated, regenerate with 'make all-mo'" if File.mtime(po) > File.mtime(mo)
This causes a build failure:
```
[!] There was an error while loading `foreman_discovery.gemspec`: No such file or directory @ rb_file_s_mtime - locale/cs_CZ/LC_MESSAGES/foreman_discovery.mo. Bundler cannot continue.
```

I think the line above it (`File.exist?`) should stop processing.

2023-06-05 14:27 UTC, stejskalleos commented
@adamruzicka review please

2023-06-05 15:09 UTC, adamruzicka approved these changes
One question, but the changes look sane

2023-06-05 15:09 UTC, adamruzicka commented on foreman_discovery.gemspec
> -# Describe your gem and declare its dependencies:
Why?

2023-06-05 15:26 UTC, adamruzicka commented
Also, not sure what's up with the tests

2023-06-06 08:59 UTC, stejskalleos commented on foreman_discovery.gemspec
> -# Describe your gem and declare its dependencies:
I was doing cleanup and was maybe too hasty. I'll revert the change.

2023-06-06 12:48 UTC, stejskalleos commented
Updated. Failing tests are not related, I'm planning to move to github actions anyway, but don't want to block this PR by it.

2023-06-07 09:41 UTC, adamruzicka approved these changes
LGTM

2023-06-08 06:56 UTC, ares approved these changes
lgtm

2023-06-08 07:00 UTC, merged