Fix rubocop offenses
theforeman/foreman_discovery pull request #614
Opened 2024-01-16 11:48 UTC by archanaserver

2024-01-16 12:01 UTC, archanaserver commented
I can see one rubocop offense on this cop `Style/SlicingWithRange` which we might have discussed in the past, https://docs.rubocop.org/rubocop/cops_style.html#styleslicingwithrange. Also this is unsafe, but what's your thought on this @ekohl, do we want this here?

And another one is `Rails/ReversibleMigration`.

2024-01-18 09:20 UTC, stejskalleos commented
Tests are failing but I guess not because of the changes here. I need to take a look what's going on there.

2024-01-18 10:29 UTC, ekohl reviewed
I think the benefit isn't really there with that cop. Looks just like a style thing to me so I'd initially ignore it. Haven't looked at the reversible cop yet

2024-01-18 10:29 UTC, ekohl commented on test/functional/discovered_hosts_controller_test.rb
> +      assert_match(/#{host.name}/, response.body)
```suggestion
      assert_includes(response.body, host.name)
```

2024-01-18 10:29 UTC, ekohl commented on test/functional/discovery_rules_controller_test.rb
> +    assert_match(/\/discovery_rules/, response.body)
```suggestion
    assert_includes(response.body, '/discovery_rules/')
```

2024-01-19 19:53 UTC, ekohl commented
We can see in https://github.com/theforeman/foreman_discovery/pull/615 that the test suite is already broken.  That makes it hard to judge if these items break anything (further) or not.

2024-01-22 09:18 UTC, stejskalleos commented
In ruby tests, there is one test that is failing everywhere:

```
Failure:
HostDiscoveredTest#test_0024_should refresh facts and NICs of an existing discovered host [foreman_discovery/test/unit/host_discovered_test.rb:274]
Minitest::Assertion: Expected: "Dishwasher DW400"
  Actual: "IBM System x -[78[70](https://github.com/theforeman/foreman_discovery/actions/runs/7602436753/job/20703002127?pr=616#step:13:71)K4G]-"
```

I will take a look during this week.

The `foreman_discovery` was failing since I am a maintainer of the repo, I tried to reproduce the problem without any success.

2024-01-23 12:36 UTC, ekohl commented
> In ruby tests, there is one test that is failing everywhere:

This is:

https://github.com/theforeman/foreman_discovery/blob/6aaa8d26a76c326f38cc87d9d40b331b1c381c57/test/unit/host_discovered_test.rb#L263-L277

It's updating the legacy fact `productname` while since https://github.com/theforeman/foreman/commit/cc4a95ffbe24ddc1bc16dd3f13ceef2a742331f9 we prefect the modern fact `dmi.product.name`. Though the fixture (https://github.com/theforeman/foreman_discovery/blob/develop/test/facts/regular_host.json) doesn't contain the modern fact at all.

2024-01-23 12:37 UTC, ekohl commented
It could also be caching facts via https://github.com/theforeman/foreman/commit/735b40161176be270934998a126b42e90c0e9724.

2024-01-23 13:20 UTC, ekohl commented
> It could also be caching facts via [theforeman/foreman@735b401](https://github.com/theforeman/foreman/commit/735b40161176be270934998a126b42e90c0e9724).

From some testing it does appear to be failing it, which I could reproduce locally. I think https://github.com/theforeman/foreman_discovery/pull/617 fixes that particular test.

2024-01-23 15:16 UTC, ekohl commented
https://github.com/theforeman/foreman_discovery/pull/618 fixes another test that has long been broken.

2024-01-29 08:14 UTC, stejskalleos commented
I merged fix for broken `rake foreman_discovery:test` , can you rebase and squash the commits?

2024-01-29 10:21 UTC, ekohl commented
@stejskalleos I wouldn't squash commits because it's easier to review the changes per cop

2024-02-05 10:56 UTC, stejskalleos reviewed
@archanaserver can you rebase please so the CI will get run on the latest changes?
(You don't have to squash the commits, as Ewoud said)

2024-02-05 18:47 UTC, archanaserver commented
@stejskalleos it is rebased and running on the latest changes.

The checks are failing due to some webpack changes, I have looked into it, this seems like some routing issue and I'm not sure what is the exact issue here. Would you mind taking a look here?

2024-04-03 13:19 UTC, archanaserver commented
@ekohl i can't find why it is failing clearly, would you please help me here?

2024-04-05 12:25 UTC, ekohl requested changes
As you noted, we see the failures in other places too. It's being worked on. It doesn't have to block merging.

2024-04-05 12:25 UTC, ekohl commented on test/functional/discovery_rules_controller_test.rb
> +  end
You can drop this since https://github.com/theforeman/foreman_discovery/pull/618 removed the assertion and created a better one.

2024-05-09 06:09 UTC, archanaserver commented
@ekohl @stejskalleos would you mind taking a look on the final changes?

2024-05-10 12:10 UTC, ekohl approved these changes
@stejskalleos?

2024-05-13 05:33 UTC, merged

2024-05-13 05:33 UTC, stejskalleos commented
Thanks @archanaserver @ekohl